-- Drop the table if it exists to ensure a clean start
DROP TABLE IF EXISTS public.community_notes;

-- Create the community_notes table
CREATE TABLE public.community_notes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    record_id uuid NOT NULL,
    user_id uuid NOT NULL,
    note text NOT NULL
);

-- Set ownership
ALTER TABLE public.community_notes OWNER TO postgres;

-- Configure the primary key sequence
ALTER TABLE public.community_notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.community_notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Add constraints including the crucial foreign keys
ALTER TABLE ONLY public.community_notes
    ADD CONSTRAINT community_notes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.community_notes
    ADD CONSTRAINT community_notes_record_id_fkey FOREIGN KEY (record_id) REFERENCES public.records(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.community_notes
    ADD CONSTRAINT community_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id) ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE public.community_notes ENABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON TABLE public.community_notes TO authenticated;

-- Policies for community_notes
CREATE POLICY "Enable insert for community managers on their records"
ON public.community_notes FOR INSERT TO authenticated
WITH CHECK (
  (get_my_claim('user_role'::text) = '"community_manager"'::jsonb)
  AND
  (EXISTS ( SELECT 1
   FROM records r
  WHERE ((r.id = community_notes.record_id) AND (r.community_id = trim(both '"' from (get_my_claim('community_id'::text))::text)::uuid))))
);

CREATE POLICY "Enable insert for admin"
ON public.community_notes FOR INSERT TO authenticated
WITH CHECK (
  (get_my_claim('user_role'::text) = '"admin"'::jsonb)
);

CREATE POLICY "Enable select for admin and tiferet david"
ON public.community_notes FOR SELECT TO authenticated
USING (
  (get_my_claim('user_role'::text) = '"admin"'::jsonb)
  OR
  (get_my_claim('user_role'::text) = '"tiferet_david"'::jsonb)
);
