-- Create a new table to hold records that fail validation during sync
CREATE TABLE public.unresolved_records (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_data jsonb,
    error_reason text,
    is_resolved boolean DEFAULT false NOT NULL
);

-- Set ownership
ALTER TABLE public.unresolved_records OWNER TO postgres;

-- Configure the primary key sequence
ALTER TABLE public.unresolved_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unresolved_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Add primary key
ALTER TABLE ONLY public.unresolved_records
    ADD CONSTRAINT unresolved_records_pkey PRIMARY KEY (id);

-- Enable RLS
ALTER TABLE public.unresolved_records ENABLE ROW LEVEL SECURITY;

-- Grant permissions to authenticated users
GRANT ALL ON TABLE public.unresolved_records TO authenticated;

-- Policies for unresolved_records: only admins can view and manage them
CREATE POLICY "Enable all for admin"
ON public.unresolved_records FOR ALL TO authenticated
USING (
  (get_my_claim('user_role'::text) = '"admin"'::jsonb)
);
