-- Drop existing table if it was created in error before, to ensure a clean slate.
DROP TABLE IF EXISTS public.td_notes;

-- Create the td_notes table to store notes from Tiferet David and Admins
CREATE TABLE public.td_notes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    record_id uuid NOT NULL,
    user_id uuid NOT NULL,
    note text NOT NULL
);

-- Set ownership
ALTER TABLE public.td_notes OWNER TO postgres;

-- Configure the primary key sequence
ALTER TABLE public.td_notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.td_notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Add constraints
ALTER TABLE ONLY public.td_notes
    ADD CONSTRAINT td_notes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.td_notes
    ADD CONSTRAINT td_notes_record_id_fkey FOREIGN KEY (record_id) REFERENCES public.records(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.td_notes
    ADD CONSTRAINT td_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id) ON DELETE CASCADE;

-- Enable Row Level Security
ALTER TABLE public.td_notes ENABLE ROW LEVEL SECURITY;

-- Grant all permissions to authenticated users, to be restricted by policies
GRANT ALL ON TABLE public.td_notes TO authenticated;

-- Create Policies for td_notes
CREATE POLICY "Enable read for admin and tiferet david"
ON public.td_notes FOR SELECT TO authenticated
USING (
  (get_my_claim('user_role'::text) = '"admin"'::jsonb)
  OR
  (get_my_claim('user_role'::text) = '"tiferet_david"'::jsonb)
);

CREATE POLICY "Enable insert for admin and tiferet david"
ON public.td_notes FOR INSERT TO authenticated
WITH CHECK (
  (get_my_claim('user_role'::text) = '"admin"'::jsonb)
  OR
  (get_my_claim('user_role'::text) = '"tiferet_david"'::jsonb)
);

CREATE POLICY "Enable update for admin and tiferet david"
ON public.td_notes FOR UPDATE TO authenticated
USING (
  (get_my_claim('user_role'::text) = '"admin"'::jsonb)
  OR
  (get_my_claim('user_role'::text) = '"tiferet_david"'::jsonb)
);

CREATE POLICY "Enable delete for admin and tiferet david"
ON public.td_notes FOR DELETE TO authenticated
USING (
  (get_my_claim('user_role'::text) = '"admin"'::jsonb)
  OR
  (get_my_claim('user_role'::text) = '"tiferet_david"'::jsonb)
);

-- Note: No migration is created for old `records.td_notes` data. This is a fresh start.
-- The old field can be removed from the UI and eventually from the table.
